# =============================================
# Storage Service - Files API (port 3005)
# =============================================

@baseUrl = http://localhost:3005/api/files
@fileId = 662927b0ffe4e19093c1963b

###

# Upload a file
POST {{baseUrl}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file-uploader-api.http"

< ./file-uploader-api.http

--boundary--

###

# Get file by ID
GET {{baseUrl}}/{{fileId}} HTTP/1.1

###
